version: '3'

tasks:
  build:
    desc: Build the desktop automation binary
    cmds:
      - mkdir -p bin
      - go build -o bin/desktop-automation ./cmd/desktop-automation

  run:
    desc: Run the desktop automation tool
    deps: [build]
    cmds:
      - ./bin/desktop-automation {{.CLI_ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf dist/
